#!/bin/sh

clear

#Сбрасываем и определяем цвет выделения
tput sgr 0;
rcolor='\e[32m'; ncolor='\e[0m';

echo -e "\e[1mSnappyCleaner\e[0m"
echo -e "------------------------------------------------"

if [[ $LANG == "ru_RU.UTF-8" ]]; then
#Очищаю временные файлы root
  echo -en "Очищаю временные файлы root... "
  rm -rf /root/tmp/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю корзину
  echo -en "Очищаю корзину пользователя... "
  rm -rf /home/$(logname)/.local/share/Trash/files/*
  rm -rf /home/$(logname)/.local/share/Trash/info/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю временные файлы пользователя
  echo -en "Очищаю временные файлы пользователя... "
  rm -rf /home/$(logname)/tmp/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю временные файлы пользователя RecentDocuments и recent*.xbel
  echo -en "Очищаю Последние Документы... "
  rm -rf /home/$(logname)/.local/share/RecentDocuments/*
  rm -rf /home/$(logname)/.local/share/recent*.xbel
  echo -e "${rcolor}завершено${ncolor}\n"

#Ремонтирую базу данных RPM
  echo -en "Ремонтирую базу данных RPM... "
  rm -f /var/lib/rpm/__db*; /usr/bin/rpm --rebuilddb;
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш urpmi
  echo -en "Очищаю кеш URPMI... "
  /usr/sbin/urpmi --clean;
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш dnf
  echo -en "Очищаю кеш DNF... "
  /usr/bin/dnf clean all 2>&1 >/dev/null;
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш Mozilla Firefox
  echo -en "Очищаю кеш браузера Mozilla Firefox... "
  rm -rf /home/$(logname)/.cache/mozilla/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш Google Chrome
  echo -en "Очищаю кеш браузера Google Chrome... "
  rm -rf /home/$(logname)/.cache/google-chrome/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш Opera
  echo -en "Очищаю кеш браузера Opera... "
  rm -rf /home/$(logname)/.cache/opera/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш Chromium
  echo -en "Очищаю кеш браузера Chromium... "
  rm -rf /home/$(logname)/.cache/chromium/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш PaleMoon
  echo -en "Очищаю кеш браузера PaleMoon... "
  rm -rf "/home/$(logname)/.cache/moonchild productions/"*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш Brave
  echo -en "Очищаю кеш браузера Brave... "
  rm -rf /home/$(logname)/.cache/BraveSoftware/Brave-Browser/Default/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю ~/.cache/thumbnails/*
  echo -en "Очищаю ~/.cache/thumbnails/* "
  rm -rf /home/$(logname)/.cache/thumbnails/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Завершаю очистку
  echo "------------------------------------------------"
  echo -e ${rcolor}"Очистка завершена${ncolor}\n"
exit
fi;

#Очищаю временные файлы root
  echo -en "Clean temporary root files... "
  rm -rf /root/tmp/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю корзину
  echo -en "Clean the user recycle bin... "
  rm -rf /home/$(logname)/.local/share/Trash/files/*
  rm -rf /home/$(logname)/.local/share/Trash/info/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю временные файлы пользователя
  echo -en "Clean user temporary files... "
  rm -rf /home/$(logname)/tmp/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю временные файлы пользователя RecentDocuments и recent*.xbel
  echo -en "Clean Recent Documents... "
  rm -rf /home/$(logname)/.local/share/RecentDocuments/*
  rm -rf /home/$(logname)/.local/share/recent*.xbel
  echo -e "${rcolor}completed${ncolor}\n"

#Ремонтирую базу данных RPM
  echo -en "Repair RPM DataBase... "
  rm -f /var/lib/rpm/__db*; /usr/bin/rpm --rebuilddb;
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш urpmi
  echo -en "Clean URPMI cache... "
  /usr/sbin/urpmi --clean;
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш dnf
  echo -en "Clean DNF cache... "
  /usr/bin/dnf clean all 2>&1 >/dev/null;
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш Mozilla Firefox
  echo -en "Clean Mozilla Firefox cache... "
  rm -rf /home/$(logname)/.cache/mozilla/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш Google Chrome
  echo -en "Clean Google Chrome cache... "
  rm -rf /home/$(logname)/.cache/google-chrome/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш Opera
  echo -en "Clean Opera cache... "
  rm -rf /home/$(logname)/.cache/opera/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш Chromium
  echo -en "Clean Chromium cache... "
  rm -rf /home/$(logname)/.cache/chromium/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш PaleMoon
  echo -en "Clean PaleMoon cache... "
  rm -rf "/home/$(logname)/.cache/moonchild productions/"*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш Brave
  echo -en "Clean Brave browser cache... "
  rm -rf /home/$(logname)/.cache/BraveSoftware/Brave-Browser/Default/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш ~/.cache/thumbnails/*
  echo -en "Clean ~/.cache/thumbnails/* "
  rm -rf /home/$(logname)/.cache/thumbnails/*
  echo -e "${rcolor}completed${ncolor}\n"


#Завершаю очистку
  echo "------------------------------------------------"
  echo -e ${rcolor}"Cleanup completed${ncolor}\n"
exit
