#!/bin/sh

clear

#Сбрасываем и определяем цвет выделения
tput sgr 0;
rcolor='\e[31m'; ncolor='\e[0m';

echo -e "\e[1mSnappyCleaner\e[0m"
echo -e "------------------------------------------------"

if [[ $LANG == "ru_RU.UTF-8" ]]; then
#Очищаю временные файлы root
  echo -en "Очищаю временные файлы root... "
  rm -rf /root/tmp/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю корзину
  echo -en "Очищаю корзину пользователя... "
  rm -rf /home/$USER/.local/share/Trash/files/*
  rm -rf /home/$USER/.local/share/Trash/info/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю временные файлы пользователя
  echo -en "Очищаю временные файлы пользователя... "
  rm -rf /home/$USER/tmp/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю временные файлы пользователя RecentDocuments
  echo -en "Очищаю файлы пользователя RecentDocuments... "
  rm -rf /home/$USER/.local/share/RecentDocuments/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Ремонтирую базу данных RPM
  echo -en "Ремонтирую базу данных RPM... "
  rm -f /var/lib/rpm/__db*; /usr/bin/rpm --rebuilddb;
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш urpmi
  echo -en "Очищаю кеш URPMI... "
  /usr/sbin/urpmi --clean;
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш Mozilla Firefox
  echo -en "Очищаю кеш браузера Mozilla Firefox... "
  rm -rf /home/$USER/.cache/mozilla/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш Google Chrome
  echo -en "Очищаю кеш браузера Google Chrome... "
  rm -rf /home/$USER/.cache/google-chrome/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш Opera
  echo -en "Очищаю кеш браузера Opera... "
  rm -rf /home/$USER/.cache/opera/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш Chromium
  echo -en "Очищаю кеш браузера Chromium... "
  rm -rf /home/$USER/.cache/chromium/*
  echo -e "${rcolor}завершено${ncolor}\n"

#Очищаю кеш PaleMoon
  echo -en "Очищаю кеш браузера PaleMoon... "
  rm -rf "/home/$USER/.cache/moonchild productions/"*
  echo -e "${rcolor}завершено${ncolor}\n"

#Завершаю очистку
  echo "------------------------------------------------"
  echo -e ${rcolor}"Очистка завершена${ncolor}\n"
exit
fi;

#Очищаю временные файлы root
  echo -en "Clean temporary root files... "
  rm -rf /root/tmp/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю корзину
  echo -en "Clean the user recycle bin... "
  rm -rf /home/$USER/.local/share/Trash/files/*
  rm -rf /home/$USER/.local/share/Trash/info/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю временные файлы пользователя
  echo -en "Clean user temporary files... "
  rm -rf /home/$USER/tmp/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю временные файлы пользователя RecentDocuments
  echo -en "Clean RecentDocuments... "
  rm -rf /home/$USER/.local/share/RecentDocuments/*
  echo -e "${rcolor}completed${ncolor}\n"

#Ремонтирую базу данных RPM
  echo -en "Repair RPM DataBase... "
  rm -f /var/lib/rpm/__db*; /usr/bin/rpm --rebuilddb;
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш urpmi
  echo -en "Clean URPMI cache... "
  /usr/sbin/urpmi --clean;
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш Mozilla Firefox
  echo -en "Clean Mozilla Firefox cache... "
  rm -rf /home/$USER/.cache/mozilla/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш Google Chrome
  echo -en "Clean Google Chrome cache... "
  rm -rf /home/$USER/.cache/google-chrome/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш Opera
  echo -en "Clean Opera cache... "
  rm -rf /home/$USER/.cache/opera/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш Chromium
  echo -en "Clean Chromium cache... "
  rm -rf /home/$USER/.cache/chromium/*
  echo -e "${rcolor}completed${ncolor}\n"

#Очищаю кеш PaleMoon
  echo -en "Clean PaleMoon cache... "
  rm -rf "/home/$USER/.cache/moonchild productions/"*
  echo -e "${rcolor}completed${ncolor}\n"

#Завершаю очистку
  echo "------------------------------------------------"
  echo -e ${rcolor}"Cleanup completed${ncolor}\n"
exit